Traceback (most recent call last):
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/lockfile/pidlockfile.py", line 77, in acquire
    write_pid_to_pidfile(self.path)
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/lockfile/pidlockfile.py", line 161, in write_pid_to_pidfile
    pidfile_fd = os.open(pidfile_path, open_flags, open_mode)
PermissionError: [Errno 13] Permission denied: './airflow-webserver-monitor.pid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/bin/airflow", line 10, in <module>
    sys.exit(main())
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/airflow/__main__.py", line 39, in main
    args.func(args)
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/airflow/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 108, in wrapper
    return f(*args, **kwargs)
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 476, in webserver
    with ctx:
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/daemon/daemon.py", line 365, in __enter__
    self.open()
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/daemon/daemon.py", line 357, in open
    self.pidfile.__enter__()
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/daemon/pidfile.py", line 49, in acquire
    super().acquire(timeout, *args, **kwargs)
  File "/media/prempeh/Nouveau nom/MASTER2/DATA ENGINEERING/airflow/py_env/lib/python3.10/site-packages/lockfile/pidlockfile.py", line 91, in acquire
    raise LockFailed("failed to create %s" % self.path)
lockfile.LockFailed: failed to create ./airflow-webserver-monitor.pid
